# -*- coding: utf-8 -*-
"""Tema1_TodascaEvelyne.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T3tu2SQezpR6OT4AlZOE-EDxUUGNXcPx
"""

!pip install yahoo_fin

import warnings
warnings.simplefilter("ignore")

import yahoo_fin as yf
from yahoo_fin.stock_info import *
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as scs
from scipy.stats import skew
from scipy.stats import kurtosis

start = datetime.datetime(2012,1,1)
end = datetime.datetime(2022,1,1)

stock_Nike = get_data('NKE' , start_date = start, end_date = end)
print(stock_Nike.head())

stock_Nike=stock_Nike.dropna()
close_Nike = pd.DataFrame(stock_Nike["close"]).dropna()
simple_return_Nike = close_Nike.pct_change().dropna()
log_return_Nike = np.log(1+simple_return_Nike)
#print(simple_return_Nike)
#print(log_return_Nike)

stock_Adidas = get_data('ADDYY' , start_date = start, end_date = end)
print(stock_Adidas.head())

stock_Adidas=stock_Adidas.dropna()
close_Adidas = pd.DataFrame(stock_Adidas["close"]).dropna()
simple_return_Adidas = close_Adidas.pct_change().dropna()
log_return_Adidas = np.log(1+simple_return_Adidas)
#print(simple_return_Adidas)
#print(log_return_Adidas)

plt.figure(figsize=(18, 10))
simple_return_Nike['close'].plot(label='Nike', color='pink',grid=False)
simple_return_Adidas['close'].plot(label='Adidas',grid=False)
plt.legend()

fig = sns.distplot(log_return_Adidas, kde=True, norm_hist=True)                                    
fig.set_title('Distribution of Adidas returns', fontsize=16)

print('Skewness:')
print(skew(log_return_Adidas))
print('Kurtosis:')
print(kurtosis(log_return_Adidas))

"""Distributia este leptocurtica si are o asimetrie negativa.

"""

fig = sns.distplot(log_return_Nike, kde=True, norm_hist=True, color='pink')                                    
fig.set_title('Distribution of Nike returns', fontsize=16)

print('Skewness:')
print(skew(log_return_Nike))
print('Kurtosis:')
print(kurtosis(log_return_Nike))